# Generated by Django 5.1.5 on 2025-01-21 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenstrualCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_period', models.DateField()),
                ('cycle_length', models.IntegerField(help_text='Cycle length in days')),
                ('period_duration', models.IntegerField(help_text='Duration of period in days')),
                ('cycle_regular', models.BooleanField(help_text='Is the cycle regular?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menstrual_cycle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
